theme = "plant-community"
baseURL = "http://piedmontprairie.netlify.app"
languageCode = "en-us"
title = "Piedmont Prairie"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$",  "\\.utf8\\.md$", "_cache$"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/bsaul/piedmontprairie.us"
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Parthenium-integrifolium-0.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
